<?php

namespace backend\modules\market\forms;

use common\models\market\MarketCard;
use yii\validators\NumberValidator;
use yii\validators\Validator;

class CardFrom extends MarketCard
{
    public $show_max_use_time = 0;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['count', 'amount','start_time', 'end_time', 'goods_type_attach', 'batch', 'area_attach'], 'required'],
            [['count', 'amount', 'max_use_time'], 'integer'],
            [['batch'], 'string', 'max' => 50],
            [['batch'], 'validateBatch'],
            [['batch','area_attach'], 'safe'],
            [['start_time','end_time'], 'date'],
            [['start_time', 'end_time'], 'validateEndTime'],
            [['show_max_use_time'], 'validateMaxUseTime'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'batch' => '批次',
            'count' => '生成数量',
            'amount' => '金额',
            'goods_type_attach' => '产品线',
            'start_time' => '开始时间',
            'end_time' => '结束时间',
            'max_use_time' => '最长使用时间',
            'area_attach' => '活动站点地区',
        ];
    }

    public function validateEndTime($attribute)
    {
        if(!empty($this->end_time) && !empty($this->start_time) && $this->end_time <= $this->start_time) {
            $this->addError($attribute, '结束时间必需大于开始时间');
        }
    }

    public function validateBatch($attribute)
    {
        if(MarketCard::findOne(['batch'=>$this->batch])) {
            $this->addError($attribute, \Yii::t('card','批次已生成'));
        }
    }

    public function validateMaxUseTime($attribute)
    {
        if($this->show_max_use_time) {
            if(empty($this->max_use_time)) {
                $this->addError('max_use_time', '不能为空');
                return;
            }

            if(!empty($this->start_time) && !empty($this->end_time)) {
                $start_time = strtotime($this->start_time);
                $end_time = strtotime($this->end_time);

                if(($end_time-$start_time) <= ($this->max_use_time*86400)) {
                    $this->addError('max_use_time', '不能大于开始和结束时间的差');
                }
            }
        }
    }

    public function afterValidate()
    {
        if(!empty($this->max_use_time)) {
            $this->setAttribute('max_use_time' , $this->max_use_time*86400);
        }
        else {
            $this->setAttribute('max_use_time' , 0);
        }
        $this->setAttribute('start_time' , strtotime($this->start_time));
        $this->setAttribute('end_time' , strtotime($this->end_time .' +1 day'));
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
}